"""GFEM version added

Revision ID: a9485f675323
Revises: 
Create Date: 2023-03-16 15:49:26.529686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9485f675323'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_structure',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('frame',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('number'),
    sa.UniqueConstraint('number')
    )
    op.create_table('material',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('time_created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('eu', sa.Float(), nullable=False),
    sa.Column('nu', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('stringer',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('number', 'side', name='stringer_reference')
    )
    op.create_table('mass',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('time_created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('coord_x', sa.Float(), nullable=False),
    sa.Column('coord_y', sa.Float(), nullable=False),
    sa.Column('coord_z', sa.Float(), nullable=False),
    sa.Column('stringer', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('frame', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['frame'], ['frame.number'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stringer', 'side'], ['stringer.number', 'stringer.side'], name='stringer_reference'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('node',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('time_created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('coord_x', sa.Float(), nullable=False),
    sa.Column('coord_y', sa.Float(), nullable=False),
    sa.Column('coord_z', sa.Float(), nullable=False),
    sa.Column('stringer', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=3), nullable=False),
    sa.Column('frame', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['frame'], ['frame.number'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stringer', 'side'], ['stringer.number', 'stringer.side'], name='stringer_reference'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('section_property',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('time_created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('coord_x', sa.Float(), nullable=False),
    sa.Column('coord_y', sa.Float(), nullable=False),
    sa.Column('coord_z', sa.Float(), nullable=False),
    sa.Column('stringer', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=3), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('A', sa.Float(), nullable=True),
    sa.Column('I1', sa.Float(), nullable=True),
    sa.Column('I2', sa.Float(), nullable=True),
    sa.Column('I12', sa.Float(), nullable=True),
    sa.Column('J', sa.Float(), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('Imin', sa.Float(), nullable=True),
    sa.Column('Imax', sa.Float(), nullable=True),
    sa.Column('frame', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['frame'], ['frame.number'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stringer', 'side'], ['stringer.number', 'stringer.side'], name='stringer_reference'),
    sa.ForeignKeyConstraint(['type'], ['base_structure.name'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('sections',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('time_created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('coord_x', sa.Float(), nullable=False),
    sa.Column('coord_y', sa.Float(), nullable=False),
    sa.Column('coord_z', sa.Float(), nullable=False),
    sa.Column('stringer', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=3), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('width_1', sa.Float(), nullable=False),
    sa.Column('th_1', sa.Float(), nullable=True),
    sa.Column('width_2', sa.Float(), nullable=True),
    sa.Column('th_2', sa.Float(), nullable=True),
    sa.Column('width_3', sa.Float(), nullable=True),
    sa.Column('th_3', sa.Float(), nullable=True),
    sa.Column('width_4', sa.Float(), nullable=True),
    sa.Column('th_4', sa.Float(), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('frame', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['frame'], ['frame.number'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stringer', 'side'], ['stringer.number', 'stringer.side'], name='stringer_reference'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('structure_table',
    sa.Column('struct_type', sa.String(length=20), nullable=False),
    sa.Column('number', sa.Float(precision=1), nullable=False),
    sa.Column('side', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['struct_type'], ['base_structure.name'], ),
    sa.PrimaryKeyConstraint('struct_type', 'number', 'side', name='unique_reference')
    )
    op.create_table('property',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('time_created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('material', sa.Integer(), nullable=True),
    sa.Column('shell_thick', sa.Float(), nullable=True),
    sa.Column('start_property', sa.Integer(), nullable=True),
    sa.Column('end_property', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['end_property'], ['section_property.uid'], ),
    sa.ForeignKeyConstraint(['material'], ['material.uid'], ),
    sa.ForeignKeyConstraint(['start_property'], ['section_property.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('element',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('time_created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('base_structure', sa.String(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('offset_start', sa.Float(), nullable=True),
    sa.Column('offset_end', sa.Float(), nullable=True),
    sa.Column('node_1', sa.Integer(), nullable=True),
    sa.Column('node_2', sa.Integer(), nullable=True),
    sa.Column('node_3', sa.Integer(), nullable=True),
    sa.Column('node_4', sa.Integer(), nullable=True),
    sa.Column('off_1_x', sa.Float(), nullable=True),
    sa.Column('off_1_y', sa.Float(), nullable=True),
    sa.Column('off_1_z', sa.Float(), nullable=True),
    sa.Column('off_2_x', sa.Float(), nullable=True),
    sa.Column('off_2_y', sa.Float(), nullable=True),
    sa.Column('off_2_z', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['base_structure'], ['base_structure.name'], ),
    sa.ForeignKeyConstraint(['node_1'], ['node.uid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_2'], ['node.uid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_3'], ['node.uid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_4'], ['node.uid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pid'], ['property.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('element')
    op.drop_table('property')
    op.drop_table('structure_table')
    op.drop_table('sections')
    op.drop_table('section_property')
    op.drop_table('node')
    op.drop_table('mass')
    op.drop_table('stringer')
    op.drop_table('material')
    op.drop_table('frame')
    op.drop_table('base_structure')
    # ### end Alembic commands ###
