"""change tables

Revision ID: ba57e6f3acc1
Revises: 4f152fd224ab
Create Date: 2023-03-28 15:49:14.656292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba57e6f3acc1'
down_revision = '4f152fd224ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SectionPropertyMap',
    sa.Column('frame', sa.Integer(), nullable=False),
    sa.Column('sec_prop_uid', sa.Integer(), nullable=False),
    sa.Column('stringer', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['frame'], ['frame.number'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sec_prop_uid'], ['section_property.uid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stringer', 'side'], ['stringer.number', 'stringer.side'], name='stringer_reference'),
    sa.PrimaryKeyConstraint('frame', 'sec_prop_uid', 'stringer', 'side')
    )
    op.drop_table('SectionPropertyReference')
    op.alter_column('element', 'node_1',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('section_property', sa.Column('Ref_Geometry', sa.String(), nullable=True))
    op.drop_constraint('section_property_type_fkey', 'section_property', type_='foreignkey')
    op.create_foreign_key(None, 'section_property', 'base_structure', ['Ref_Geometry'], ['name'])
    op.add_column('sections', sa.Column('Ref_Geometry', sa.String(), nullable=True))
    op.create_foreign_key(None, 'sections', 'base_structure', ['Ref_Geometry'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_column('sections', 'Ref_Geometry')
    op.drop_constraint(None, 'section_property', type_='foreignkey')
    op.create_foreign_key('section_property_type_fkey', 'section_property', 'base_structure', ['type'], ['name'])
    op.drop_column('section_property', 'Ref_Geometry')
    op.alter_column('element', 'node_1',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('SectionPropertyReference',
    sa.Column('frame', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sec_prop_uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stringer', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('side', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['frame'], ['frame.number'], name='SectionPropertyReference_frame_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sec_prop_uid'], ['section_property.uid'], name='SectionPropertyReference_sec_prop_uid_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stringer', 'side'], ['stringer.number', 'stringer.side'], name='stringer_reference'),
    sa.PrimaryKeyConstraint('frame', 'sec_prop_uid', 'stringer', 'side', name='SectionPropertyReference_pkey')
    )
    op.drop_table('SectionPropertyMap')
    # ### end Alembic commands ###
