"""Element offset delete

Revision ID: caca3593fc24
Revises: dcba01bcc4f2
Create Date: 2023-03-29 16:41:46.750067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'caca3593fc24'
down_revision = 'dcba01bcc4f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('element', 'offset_end')
    op.drop_column('element', 'offset_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('element', sa.Column('offset_start', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('element', sa.Column('offset_end', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
