"""SecPropMap_update

Revision ID: dcba01bcc4f2
Revises: ba57e6f3acc1
Create Date: 2023-03-29 10:31:54.806620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcba01bcc4f2'
down_revision = 'ba57e6f3acc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SectionPropertyMap', sa.Column('uid', sa.Integer(), nullable=False))
    op.drop_constraint('SectionPropertyMap_sec_prop_uid_fkey', 'SectionPropertyMap', type_='foreignkey')
    op.create_foreign_key(None, 'SectionPropertyMap', 'section_property', ['uid'], ['uid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('SectionPropertyMap', 'sec_prop_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SectionPropertyMap', sa.Column('sec_prop_uid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'SectionPropertyMap', type_='foreignkey')
    op.create_foreign_key('SectionPropertyMap_sec_prop_uid_fkey', 'SectionPropertyMap', 'section_property', ['sec_prop_uid'], ['uid'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('SectionPropertyMap', 'uid')
    # ### end Alembic commands ###
